export const VALID_FIELDS = {
  TENANT: [
    "id",
    "name",
    "email",
    "phone",
    "address",
    "timezone",
    "createdAt",
    "updatedAt",
  ],
  USER: ["id", "tenantId", "roleId", "name", "email", "createdAt", "updatedAt"],
  ROLE: ["id", "name", "createdAt", "updatedAt"],
  ENQUIRY: [
    "id",
    "subject",
    "message",
    "channel",
    "source",
    "status",
    "tenantId",
    "createdAt",
  ],
  LEAD: [
    "id",
    "name",
    "email",
    "phone",
    "pipelineId",
    "enquiryId",
    "tenantId",
    "createdBy",
    "createdAt",
    "updatedAt",
  ],
  DEAL: [
    "id",
    "tenantId",
    "leadId",
    "name",
    "stage",
    "value",
    "currency",
    "ownerId",
    "createdBy",
    "createdAt",
    "updatedAt",
  ],
};
